// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"latihan-golang-restful-api-nkw/app"
	"latihan-golang-restful-api-nkw/controller"
	"latihan-golang-restful-api-nkw/middleware"
	"latihan-golang-restful-api-nkw/repository"
	"latihan-golang-restful-api-nkw/service"
	"net/http"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from injector.go:

func InitializerServer() *http.Server {
	factoryMasterRepositoryImpl := repository.NewFactoryMasterRepository()
	db := app.NewDB()
	factoryMasterServiceImpl := service.NewFactoryMasterService(factoryMasterRepositoryImpl, db)
	factoryMasterControllerImpl := controller.NewFactoryMasterController(factoryMasterServiceImpl)
	router := app.NewRouterFactoryMasters(factoryMasterControllerImpl)
	authMiddleware := middleware.NewAuthMiddleware(router)
	server := NewServer(authMiddleware)
	return server
}

// injector.go:

var weavingKainMasterSet = wire.NewSet(repository.NewWeavingKainMasterRepository, wire.Bind(new(repository.WeavingKainMasterRepository), new(*repository.WeavingKainMasterRepositoryImpl)), service.NewFactoryMasterService, wire.Bind(new(service.WeavingKainMasterService), new(*service.WeavingKainMasterServiceImpl)), controller.NewWeavingKainMasterController, wire.Bind(new(controller.WeavingKainMasterController), new(*controller.WeavingKainMasterControllerImpl)))

var factoryMasterSet = wire.NewSet(repository.NewFactoryMasterRepository, wire.Bind(new(repository.FactoryMasterRepository), new(*repository.FactoryMasterRepositoryImpl)), service.NewFactoryMasterService, wire.Bind(new(service.FactoryMasterService), new(*service.FactoryMasterServiceImpl)), controller.NewFactoryMasterController, wire.Bind(new(controller.FactoryMasterController), new(*controller.FactoryMasterControllerImpl)))
